# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.11
#
# <auto-generated>
#
# Generated from file `smarthome.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module SmartHome
_M_SmartHome = Ice.openModule('SmartHome')
__name__ = 'SmartHome'

if 'InvalidValueException' not in _M_SmartHome.__dict__:
    _M_SmartHome.InvalidValueException = Ice.createTempClass()
    class InvalidValueException(Ice.UserException):
        def __init__(self, field='', reason=''):
            self.field = field
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHome::InvalidValueException'

    _M_SmartHome._t_InvalidValueException = IcePy.defineException('::SmartHome::InvalidValueException', InvalidValueException, (), False, None, (
        ('field', (), IcePy._t_string, False, 0),
        ('reason', (), IcePy._t_string, False, 0)
    ))
    InvalidValueException._ice_type = _M_SmartHome._t_InvalidValueException

    _M_SmartHome.InvalidValueException = InvalidValueException
    del InvalidValueException

if 'OperationFailedException' not in _M_SmartHome.__dict__:
    _M_SmartHome.OperationFailedException = Ice.createTempClass()
    class OperationFailedException(Ice.UserException):
        def __init__(self, deviceId='', reason=''):
            self.deviceId = deviceId
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHome::OperationFailedException'

    _M_SmartHome._t_OperationFailedException = IcePy.defineException('::SmartHome::OperationFailedException', OperationFailedException, (), False, None, (
        ('deviceId', (), IcePy._t_string, False, 0),
        ('reason', (), IcePy._t_string, False, 0)
    ))
    OperationFailedException._ice_type = _M_SmartHome._t_OperationFailedException

    _M_SmartHome.OperationFailedException = OperationFailedException
    del OperationFailedException

if 'ThermostatMode' not in _M_SmartHome.__dict__:
    _M_SmartHome.ThermostatMode = Ice.createTempClass()
    class ThermostatMode(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    ThermostatMode.COOLING = ThermostatMode("COOLING", 0)
    ThermostatMode.HEATING = ThermostatMode("HEATING", 1)
    ThermostatMode.OFF = ThermostatMode("OFF", 2)
    ThermostatMode._enumerators = { 0:ThermostatMode.COOLING, 1:ThermostatMode.HEATING, 2:ThermostatMode.OFF }

    _M_SmartHome._t_ThermostatMode = IcePy.defineEnum('::SmartHome::ThermostatMode', ThermostatMode, (), ThermostatMode._enumerators)

    _M_SmartHome.ThermostatMode = ThermostatMode
    del ThermostatMode

if 'ThermostatReading' not in _M_SmartHome.__dict__:
    _M_SmartHome.ThermostatReading = Ice.createTempClass()
    class ThermostatReading(object):
        def __init__(self, currentTemperature=0.0, timestamp=0):
            self.currentTemperature = currentTemperature
            self.timestamp = timestamp

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_SmartHome.ThermostatReading):
                return NotImplemented
            else:
                if self.currentTemperature != other.currentTemperature:
                    return False
                if self.timestamp != other.timestamp:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_ThermostatReading)

        __repr__ = __str__

    _M_SmartHome._t_ThermostatReading = IcePy.defineStruct('::SmartHome::ThermostatReading', ThermostatReading, (), (
        ('currentTemperature', (), IcePy._t_double),
        ('timestamp', (), IcePy._t_long)
    ))

    _M_SmartHome.ThermostatReading = ThermostatReading
    del ThermostatReading

if 'ThermostatStatus' not in _M_SmartHome.__dict__:
    _M_SmartHome.ThermostatStatus = Ice.createTempClass()
    class ThermostatStatus(object):
        def __init__(self, reading=Ice._struct_marker, targetTemperature=0.0, mode=_M_SmartHome.ThermostatMode.COOLING):
            if reading is Ice._struct_marker:
                self.reading = _M_SmartHome.ThermostatReading()
            else:
                self.reading = reading
            self.targetTemperature = targetTemperature
            self.mode = mode

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_SmartHome.ThermostatStatus):
                return NotImplemented
            else:
                if self.reading != other.reading:
                    return False
                if self.targetTemperature != other.targetTemperature:
                    return False
                if self.mode != other.mode:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_ThermostatStatus)

        __repr__ = __str__

    _M_SmartHome._t_ThermostatStatus = IcePy.defineStruct('::SmartHome::ThermostatStatus', ThermostatStatus, (), (
        ('reading', (), _M_SmartHome._t_ThermostatReading),
        ('targetTemperature', (), IcePy._t_double),
        ('mode', (), _M_SmartHome._t_ThermostatMode)
    ))

    _M_SmartHome.ThermostatStatus = ThermostatStatus
    del ThermostatStatus

if '_t_ReadingHistory' not in _M_SmartHome.__dict__:
    _M_SmartHome._t_ReadingHistory = IcePy.defineSequence('::SmartHome::ReadingHistory', (), _M_SmartHome._t_ThermostatReading)

_M_SmartHome._t_Thermostat = IcePy.defineValue('::SmartHome::Thermostat', Ice.Value, -1, (), False, True, None, ())

if 'ThermostatPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.ThermostatPrx = Ice.createTempClass()
    class ThermostatPrx(Ice.ObjectPrx):

        def getStatus(self, context=None):
            return _M_SmartHome.Thermostat._op_getStatus.invoke(self, ((), context))

        def getStatusAsync(self, context=None):
            return _M_SmartHome.Thermostat._op_getStatus.invokeAsync(self, ((), context))

        def begin_getStatus(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_getStatus.begin(self, ((), _response, _ex, _sent, context))

        def end_getStatus(self, _r):
            return _M_SmartHome.Thermostat._op_getStatus.end(self, _r)

        def setTargetTemperature(self, temperature, context=None):
            return _M_SmartHome.Thermostat._op_setTargetTemperature.invoke(self, ((temperature, ), context))

        def setTargetTemperatureAsync(self, temperature, context=None):
            return _M_SmartHome.Thermostat._op_setTargetTemperature.invokeAsync(self, ((temperature, ), context))

        def begin_setTargetTemperature(self, temperature, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_setTargetTemperature.begin(self, ((temperature, ), _response, _ex, _sent, context))

        def end_setTargetTemperature(self, _r):
            return _M_SmartHome.Thermostat._op_setTargetTemperature.end(self, _r)

        def getHistory(self, lastN, context=None):
            return _M_SmartHome.Thermostat._op_getHistory.invoke(self, ((lastN, ), context))

        def getHistoryAsync(self, lastN, context=None):
            return _M_SmartHome.Thermostat._op_getHistory.invokeAsync(self, ((lastN, ), context))

        def begin_getHistory(self, lastN, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_getHistory.begin(self, ((lastN, ), _response, _ex, _sent, context))

        def end_getHistory(self, _r):
            return _M_SmartHome.Thermostat._op_getHistory.end(self, _r)

        def reset(self, context=None):
            return _M_SmartHome.Thermostat._op_reset.invoke(self, ((), context))

        def resetAsync(self, context=None):
            return _M_SmartHome.Thermostat._op_reset.invokeAsync(self, ((), context))

        def begin_reset(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.Thermostat._op_reset.begin(self, ((), _response, _ex, _sent, context))

        def end_reset(self, _r):
            return _M_SmartHome.Thermostat._op_reset.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.ThermostatPrx.ice_checkedCast(proxy, '::SmartHome::Thermostat', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.ThermostatPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::Thermostat'
    _M_SmartHome._t_ThermostatPrx = IcePy.defineProxy('::SmartHome::Thermostat', ThermostatPrx)

    _M_SmartHome.ThermostatPrx = ThermostatPrx
    del ThermostatPrx

    _M_SmartHome.Thermostat = Ice.createTempClass()
    class Thermostat(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::Thermostat')

        def ice_id(self, current=None):
            return '::SmartHome::Thermostat'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::Thermostat'

        def getStatus(self, current=None):
            raise NotImplementedError("servant method 'getStatus' not implemented")

        def setTargetTemperature(self, temperature, current=None):
            raise NotImplementedError("servant method 'setTargetTemperature' not implemented")

        def getHistory(self, lastN, current=None):
            raise NotImplementedError("servant method 'getHistory' not implemented")

        def reset(self, current=None):
            raise NotImplementedError("servant method 'reset' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_ThermostatDisp)

        __repr__ = __str__

    _M_SmartHome._t_ThermostatDisp = IcePy.defineClass('::SmartHome::Thermostat', Thermostat, (), None, ())
    Thermostat._ice_type = _M_SmartHome._t_ThermostatDisp

    Thermostat._op_getStatus = IcePy.Operation('getStatus', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_ThermostatStatus, False, 0), ())
    Thermostat._op_setTargetTemperature = IcePy.Operation('setTargetTemperature', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), IcePy._t_double, False, 0),), (), None, (_M_SmartHome._t_InvalidValueException,))
    Thermostat._op_getHistory = IcePy.Operation('getHistory', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), IcePy._t_int, False, 0),), (), ((), _M_SmartHome._t_ReadingHistory, False, 0), (_M_SmartHome._t_InvalidValueException,))
    Thermostat._op_reset = IcePy.Operation('reset', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), None, ())

    _M_SmartHome.Thermostat = Thermostat
    del Thermostat

if 'LightStatus' not in _M_SmartHome.__dict__:
    _M_SmartHome.LightStatus = Ice.createTempClass()
    class LightStatus(object):
        def __init__(self, isOn=False, brightness=0):
            self.isOn = isOn
            self.brightness = brightness

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.isOn)
            _h = 5 * _h + Ice.getHash(self.brightness)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.LightStatus):
                return NotImplemented
            else:
                if self.isOn is None or other.isOn is None:
                    if self.isOn != other.isOn:
                        return (-1 if self.isOn is None else 1)
                else:
                    if self.isOn < other.isOn:
                        return -1
                    elif self.isOn > other.isOn:
                        return 1
                if self.brightness is None or other.brightness is None:
                    if self.brightness != other.brightness:
                        return (-1 if self.brightness is None else 1)
                else:
                    if self.brightness < other.brightness:
                        return -1
                    elif self.brightness > other.brightness:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_LightStatus)

        __repr__ = __str__

    _M_SmartHome._t_LightStatus = IcePy.defineStruct('::SmartHome::LightStatus', LightStatus, (), (
        ('isOn', (), IcePy._t_bool),
        ('brightness', (), IcePy._t_int)
    ))

    _M_SmartHome.LightStatus = LightStatus
    del LightStatus

if 'TimeOfDay' not in _M_SmartHome.__dict__:
    _M_SmartHome.TimeOfDay = Ice.createTempClass()
    class TimeOfDay(object):
        def __init__(self, hour=0, minute=0):
            self.hour = hour
            self.minute = minute

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.hour)
            _h = 5 * _h + Ice.getHash(self.minute)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.TimeOfDay):
                return NotImplemented
            else:
                if self.hour is None or other.hour is None:
                    if self.hour != other.hour:
                        return (-1 if self.hour is None else 1)
                else:
                    if self.hour < other.hour:
                        return -1
                    elif self.hour > other.hour:
                        return 1
                if self.minute is None or other.minute is None:
                    if self.minute != other.minute:
                        return (-1 if self.minute is None else 1)
                else:
                    if self.minute < other.minute:
                        return -1
                    elif self.minute > other.minute:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_TimeOfDay)

        __repr__ = __str__

    _M_SmartHome._t_TimeOfDay = IcePy.defineStruct('::SmartHome::TimeOfDay', TimeOfDay, (), (
        ('hour', (), IcePy._t_int),
        ('minute', (), IcePy._t_int)
    ))

    _M_SmartHome.TimeOfDay = TimeOfDay
    del TimeOfDay

if 'Schedule' not in _M_SmartHome.__dict__:
    _M_SmartHome.Schedule = Ice.createTempClass()
    class Schedule(object):
        def __init__(self, turnOn=Ice._struct_marker, turnOff=Ice._struct_marker):
            if turnOn is Ice._struct_marker:
                self.turnOn = _M_SmartHome.TimeOfDay()
            else:
                self.turnOn = turnOn
            if turnOff is Ice._struct_marker:
                self.turnOff = _M_SmartHome.TimeOfDay()
            else:
                self.turnOff = turnOff

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.turnOn)
            _h = 5 * _h + Ice.getHash(self.turnOff)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.Schedule):
                return NotImplemented
            else:
                if self.turnOn is None or other.turnOn is None:
                    if self.turnOn != other.turnOn:
                        return (-1 if self.turnOn is None else 1)
                else:
                    if self.turnOn < other.turnOn:
                        return -1
                    elif self.turnOn > other.turnOn:
                        return 1
                if self.turnOff is None or other.turnOff is None:
                    if self.turnOff != other.turnOff:
                        return (-1 if self.turnOff is None else 1)
                else:
                    if self.turnOff < other.turnOff:
                        return -1
                    elif self.turnOff > other.turnOff:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_Schedule)

        __repr__ = __str__

    _M_SmartHome._t_Schedule = IcePy.defineStruct('::SmartHome::Schedule', Schedule, (), (
        ('turnOn', (), _M_SmartHome._t_TimeOfDay),
        ('turnOff', (), _M_SmartHome._t_TimeOfDay)
    ))

    _M_SmartHome.Schedule = Schedule
    del Schedule

_M_SmartHome._t_DimmableLight = IcePy.defineValue('::SmartHome::DimmableLight', Ice.Value, -1, (), False, True, None, ())

if 'DimmableLightPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.DimmableLightPrx = Ice.createTempClass()
    class DimmableLightPrx(Ice.ObjectPrx):

        def getStatus(self, context=None):
            return _M_SmartHome.DimmableLight._op_getStatus.invoke(self, ((), context))

        def getStatusAsync(self, context=None):
            return _M_SmartHome.DimmableLight._op_getStatus.invokeAsync(self, ((), context))

        def begin_getStatus(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmableLight._op_getStatus.begin(self, ((), _response, _ex, _sent, context))

        def end_getStatus(self, _r):
            return _M_SmartHome.DimmableLight._op_getStatus.end(self, _r)

        def turnOn(self, context=None):
            return _M_SmartHome.DimmableLight._op_turnOn.invoke(self, ((), context))

        def turnOnAsync(self, context=None):
            return _M_SmartHome.DimmableLight._op_turnOn.invokeAsync(self, ((), context))

        def begin_turnOn(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmableLight._op_turnOn.begin(self, ((), _response, _ex, _sent, context))

        def end_turnOn(self, _r):
            return _M_SmartHome.DimmableLight._op_turnOn.end(self, _r)

        def turnOff(self, context=None):
            return _M_SmartHome.DimmableLight._op_turnOff.invoke(self, ((), context))

        def turnOffAsync(self, context=None):
            return _M_SmartHome.DimmableLight._op_turnOff.invokeAsync(self, ((), context))

        def begin_turnOff(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmableLight._op_turnOff.begin(self, ((), _response, _ex, _sent, context))

        def end_turnOff(self, _r):
            return _M_SmartHome.DimmableLight._op_turnOff.end(self, _r)

        def setBrightness(self, level, context=None):
            return _M_SmartHome.DimmableLight._op_setBrightness.invoke(self, ((level, ), context))

        def setBrightnessAsync(self, level, context=None):
            return _M_SmartHome.DimmableLight._op_setBrightness.invokeAsync(self, ((level, ), context))

        def begin_setBrightness(self, level, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmableLight._op_setBrightness.begin(self, ((level, ), _response, _ex, _sent, context))

        def end_setBrightness(self, _r):
            return _M_SmartHome.DimmableLight._op_setBrightness.end(self, _r)

        def setSchedule(self, turnOnHour, turnOffHour, context=None):
            return _M_SmartHome.DimmableLight._op_setSchedule.invoke(self, ((turnOnHour, turnOffHour), context))

        def setScheduleAsync(self, turnOnHour, turnOffHour, context=None):
            return _M_SmartHome.DimmableLight._op_setSchedule.invokeAsync(self, ((turnOnHour, turnOffHour), context))

        def begin_setSchedule(self, turnOnHour, turnOffHour, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmableLight._op_setSchedule.begin(self, ((turnOnHour, turnOffHour), _response, _ex, _sent, context))

        def end_setSchedule(self, _r):
            return _M_SmartHome.DimmableLight._op_setSchedule.end(self, _r)

        def reset(self, context=None):
            return _M_SmartHome.DimmableLight._op_reset.invoke(self, ((), context))

        def resetAsync(self, context=None):
            return _M_SmartHome.DimmableLight._op_reset.invokeAsync(self, ((), context))

        def begin_reset(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DimmableLight._op_reset.begin(self, ((), _response, _ex, _sent, context))

        def end_reset(self, _r):
            return _M_SmartHome.DimmableLight._op_reset.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.DimmableLightPrx.ice_checkedCast(proxy, '::SmartHome::DimmableLight', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.DimmableLightPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::DimmableLight'
    _M_SmartHome._t_DimmableLightPrx = IcePy.defineProxy('::SmartHome::DimmableLight', DimmableLightPrx)

    _M_SmartHome.DimmableLightPrx = DimmableLightPrx
    del DimmableLightPrx

    _M_SmartHome.DimmableLight = Ice.createTempClass()
    class DimmableLight(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::DimmableLight')

        def ice_id(self, current=None):
            return '::SmartHome::DimmableLight'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::DimmableLight'

        def getStatus(self, current=None):
            raise NotImplementedError("servant method 'getStatus' not implemented")

        def turnOn(self, current=None):
            raise NotImplementedError("servant method 'turnOn' not implemented")

        def turnOff(self, current=None):
            raise NotImplementedError("servant method 'turnOff' not implemented")

        def setBrightness(self, level, current=None):
            raise NotImplementedError("servant method 'setBrightness' not implemented")

        def setSchedule(self, turnOnHour, turnOffHour, current=None):
            raise NotImplementedError("servant method 'setSchedule' not implemented")

        def reset(self, current=None):
            raise NotImplementedError("servant method 'reset' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_DimmableLightDisp)

        __repr__ = __str__

    _M_SmartHome._t_DimmableLightDisp = IcePy.defineClass('::SmartHome::DimmableLight', DimmableLight, (), None, ())
    DimmableLight._ice_type = _M_SmartHome._t_DimmableLightDisp

    DimmableLight._op_getStatus = IcePy.Operation('getStatus', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_LightStatus, False, 0), ())
    DimmableLight._op_turnOn = IcePy.Operation('turnOn', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), None, ())
    DimmableLight._op_turnOff = IcePy.Operation('turnOff', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), None, ())
    DimmableLight._op_setBrightness = IcePy.Operation('setBrightness', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), IcePy._t_int, False, 0),), (), None, (_M_SmartHome._t_InvalidValueException,))
    DimmableLight._op_setSchedule = IcePy.Operation('setSchedule', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), _M_SmartHome._t_TimeOfDay, False, 0), ((), _M_SmartHome._t_TimeOfDay, False, 0)), (), None, (_M_SmartHome._t_InvalidValueException,))
    DimmableLight._op_reset = IcePy.Operation('reset', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_SmartHome.DimmableLight = DimmableLight
    del DimmableLight

if 'ColorRGB' not in _M_SmartHome.__dict__:
    _M_SmartHome.ColorRGB = Ice.createTempClass()
    class ColorRGB(object):
        def __init__(self, r=0, g=0, b=0):
            self.r = r
            self.g = g
            self.b = b

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.r)
            _h = 5 * _h + Ice.getHash(self.g)
            _h = 5 * _h + Ice.getHash(self.b)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.ColorRGB):
                return NotImplemented
            else:
                if self.r is None or other.r is None:
                    if self.r != other.r:
                        return (-1 if self.r is None else 1)
                else:
                    if self.r < other.r:
                        return -1
                    elif self.r > other.r:
                        return 1
                if self.g is None or other.g is None:
                    if self.g != other.g:
                        return (-1 if self.g is None else 1)
                else:
                    if self.g < other.g:
                        return -1
                    elif self.g > other.g:
                        return 1
                if self.b is None or other.b is None:
                    if self.b != other.b:
                        return (-1 if self.b is None else 1)
                else:
                    if self.b < other.b:
                        return -1
                    elif self.b > other.b:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_ColorRGB)

        __repr__ = __str__

    _M_SmartHome._t_ColorRGB = IcePy.defineStruct('::SmartHome::ColorRGB', ColorRGB, (), (
        ('r', (), IcePy._t_int),
        ('g', (), IcePy._t_int),
        ('b', (), IcePy._t_int)
    ))

    _M_SmartHome.ColorRGB = ColorRGB
    del ColorRGB

if 'RGBLightStatus' not in _M_SmartHome.__dict__:
    _M_SmartHome.RGBLightStatus = Ice.createTempClass()
    class RGBLightStatus(object):
        def __init__(self, base=Ice._struct_marker, color=Ice._struct_marker):
            if base is Ice._struct_marker:
                self.base = _M_SmartHome.LightStatus()
            else:
                self.base = base
            if color is Ice._struct_marker:
                self.color = _M_SmartHome.ColorRGB()
            else:
                self.color = color

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.base)
            _h = 5 * _h + Ice.getHash(self.color)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.RGBLightStatus):
                return NotImplemented
            else:
                if self.base is None or other.base is None:
                    if self.base != other.base:
                        return (-1 if self.base is None else 1)
                else:
                    if self.base < other.base:
                        return -1
                    elif self.base > other.base:
                        return 1
                if self.color is None or other.color is None:
                    if self.color != other.color:
                        return (-1 if self.color is None else 1)
                else:
                    if self.color < other.color:
                        return -1
                    elif self.color > other.color:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_RGBLightStatus)

        __repr__ = __str__

    _M_SmartHome._t_RGBLightStatus = IcePy.defineStruct('::SmartHome::RGBLightStatus', RGBLightStatus, (), (
        ('base', (), _M_SmartHome._t_LightStatus),
        ('color', (), _M_SmartHome._t_ColorRGB)
    ))

    _M_SmartHome.RGBLightStatus = RGBLightStatus
    del RGBLightStatus

_M_SmartHome._t_RGBLight = IcePy.defineValue('::SmartHome::RGBLight', Ice.Value, -1, (), False, True, None, ())

if 'RGBLightPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.RGBLightPrx = Ice.createTempClass()
    class RGBLightPrx(_M_SmartHome.DimmableLightPrx):

        def getRGBStatus(self, context=None):
            return _M_SmartHome.RGBLight._op_getRGBStatus.invoke(self, ((), context))

        def getRGBStatusAsync(self, context=None):
            return _M_SmartHome.RGBLight._op_getRGBStatus.invokeAsync(self, ((), context))

        def begin_getRGBStatus(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.RGBLight._op_getRGBStatus.begin(self, ((), _response, _ex, _sent, context))

        def end_getRGBStatus(self, _r):
            return _M_SmartHome.RGBLight._op_getRGBStatus.end(self, _r)

        def setColor(self, color, context=None):
            return _M_SmartHome.RGBLight._op_setColor.invoke(self, ((color, ), context))

        def setColorAsync(self, color, context=None):
            return _M_SmartHome.RGBLight._op_setColor.invokeAsync(self, ((color, ), context))

        def begin_setColor(self, color, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.RGBLight._op_setColor.begin(self, ((color, ), _response, _ex, _sent, context))

        def end_setColor(self, _r):
            return _M_SmartHome.RGBLight._op_setColor.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.RGBLightPrx.ice_checkedCast(proxy, '::SmartHome::RGBLight', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.RGBLightPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::RGBLight'
    _M_SmartHome._t_RGBLightPrx = IcePy.defineProxy('::SmartHome::RGBLight', RGBLightPrx)

    _M_SmartHome.RGBLightPrx = RGBLightPrx
    del RGBLightPrx

    _M_SmartHome.RGBLight = Ice.createTempClass()
    class RGBLight(_M_SmartHome.DimmableLight):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::DimmableLight', '::SmartHome::RGBLight')

        def ice_id(self, current=None):
            return '::SmartHome::RGBLight'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::RGBLight'

        def getRGBStatus(self, current=None):
            raise NotImplementedError("servant method 'getRGBStatus' not implemented")

        def setColor(self, color, current=None):
            raise NotImplementedError("servant method 'setColor' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_RGBLightDisp)

        __repr__ = __str__

    _M_SmartHome._t_RGBLightDisp = IcePy.defineClass('::SmartHome::RGBLight', RGBLight, (), None, (_M_SmartHome._t_DimmableLightDisp,))
    RGBLight._ice_type = _M_SmartHome._t_RGBLightDisp

    RGBLight._op_getRGBStatus = IcePy.Operation('getRGBStatus', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_RGBLightStatus, False, 0), ())
    RGBLight._op_setColor = IcePy.Operation('setColor', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), _M_SmartHome._t_ColorRGB, False, 0),), (), None, (_M_SmartHome._t_InvalidValueException,))

    _M_SmartHome.RGBLight = RGBLight
    del RGBLight

if 'CameraStatus' not in _M_SmartHome.__dict__:
    _M_SmartHome.CameraStatus = Ice.createTempClass()
    class CameraStatus(object):
        def __init__(self, isRecording=False, recordedFilesCount=0, recordingDurationMs=0):
            self.isRecording = isRecording
            self.recordedFilesCount = recordedFilesCount
            self.recordingDurationMs = recordingDurationMs

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.isRecording)
            _h = 5 * _h + Ice.getHash(self.recordedFilesCount)
            _h = 5 * _h + Ice.getHash(self.recordingDurationMs)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.CameraStatus):
                return NotImplemented
            else:
                if self.isRecording is None or other.isRecording is None:
                    if self.isRecording != other.isRecording:
                        return (-1 if self.isRecording is None else 1)
                else:
                    if self.isRecording < other.isRecording:
                        return -1
                    elif self.isRecording > other.isRecording:
                        return 1
                if self.recordedFilesCount is None or other.recordedFilesCount is None:
                    if self.recordedFilesCount != other.recordedFilesCount:
                        return (-1 if self.recordedFilesCount is None else 1)
                else:
                    if self.recordedFilesCount < other.recordedFilesCount:
                        return -1
                    elif self.recordedFilesCount > other.recordedFilesCount:
                        return 1
                if self.recordingDurationMs is None or other.recordingDurationMs is None:
                    if self.recordingDurationMs != other.recordingDurationMs:
                        return (-1 if self.recordingDurationMs is None else 1)
                else:
                    if self.recordingDurationMs < other.recordingDurationMs:
                        return -1
                    elif self.recordingDurationMs > other.recordingDurationMs:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_CameraStatus)

        __repr__ = __str__

    _M_SmartHome._t_CameraStatus = IcePy.defineStruct('::SmartHome::CameraStatus', CameraStatus, (), (
        ('isRecording', (), IcePy._t_bool),
        ('recordedFilesCount', (), IcePy._t_int),
        ('recordingDurationMs', (), IcePy._t_long)
    ))

    _M_SmartHome.CameraStatus = CameraStatus
    del CameraStatus

_M_SmartHome._t_FixedCamera = IcePy.defineValue('::SmartHome::FixedCamera', Ice.Value, -1, (), False, True, None, ())

if 'FixedCameraPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.FixedCameraPrx = Ice.createTempClass()
    class FixedCameraPrx(Ice.ObjectPrx):

        def getStatus(self, context=None):
            return _M_SmartHome.FixedCamera._op_getStatus.invoke(self, ((), context))

        def getStatusAsync(self, context=None):
            return _M_SmartHome.FixedCamera._op_getStatus.invokeAsync(self, ((), context))

        def begin_getStatus(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.FixedCamera._op_getStatus.begin(self, ((), _response, _ex, _sent, context))

        def end_getStatus(self, _r):
            return _M_SmartHome.FixedCamera._op_getStatus.end(self, _r)

        def startRecording(self, context=None):
            return _M_SmartHome.FixedCamera._op_startRecording.invoke(self, ((), context))

        def startRecordingAsync(self, context=None):
            return _M_SmartHome.FixedCamera._op_startRecording.invokeAsync(self, ((), context))

        def begin_startRecording(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.FixedCamera._op_startRecording.begin(self, ((), _response, _ex, _sent, context))

        def end_startRecording(self, _r):
            return _M_SmartHome.FixedCamera._op_startRecording.end(self, _r)

        def stopRecording(self, context=None):
            return _M_SmartHome.FixedCamera._op_stopRecording.invoke(self, ((), context))

        def stopRecordingAsync(self, context=None):
            return _M_SmartHome.FixedCamera._op_stopRecording.invokeAsync(self, ((), context))

        def begin_stopRecording(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.FixedCamera._op_stopRecording.begin(self, ((), _response, _ex, _sent, context))

        def end_stopRecording(self, _r):
            return _M_SmartHome.FixedCamera._op_stopRecording.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.FixedCameraPrx.ice_checkedCast(proxy, '::SmartHome::FixedCamera', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.FixedCameraPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::FixedCamera'
    _M_SmartHome._t_FixedCameraPrx = IcePy.defineProxy('::SmartHome::FixedCamera', FixedCameraPrx)

    _M_SmartHome.FixedCameraPrx = FixedCameraPrx
    del FixedCameraPrx

    _M_SmartHome.FixedCamera = Ice.createTempClass()
    class FixedCamera(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::FixedCamera')

        def ice_id(self, current=None):
            return '::SmartHome::FixedCamera'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::FixedCamera'

        def getStatus(self, current=None):
            raise NotImplementedError("servant method 'getStatus' not implemented")

        def startRecording(self, current=None):
            raise NotImplementedError("servant method 'startRecording' not implemented")

        def stopRecording(self, current=None):
            raise NotImplementedError("servant method 'stopRecording' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_FixedCameraDisp)

        __repr__ = __str__

    _M_SmartHome._t_FixedCameraDisp = IcePy.defineClass('::SmartHome::FixedCamera', FixedCamera, (), None, ())
    FixedCamera._ice_type = _M_SmartHome._t_FixedCameraDisp

    FixedCamera._op_getStatus = IcePy.Operation('getStatus', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_CameraStatus, False, 0), ())
    FixedCamera._op_startRecording = IcePy.Operation('startRecording', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, (_M_SmartHome._t_OperationFailedException,))
    FixedCamera._op_stopRecording = IcePy.Operation('stopRecording', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, (_M_SmartHome._t_OperationFailedException,))

    _M_SmartHome.FixedCamera = FixedCamera
    del FixedCamera

if 'PTZPosition' not in _M_SmartHome.__dict__:
    _M_SmartHome.PTZPosition = Ice.createTempClass()
    class PTZPosition(object):
        def __init__(self, pan=0.0, tilt=0.0, zoom=0):
            self.pan = pan
            self.tilt = tilt
            self.zoom = zoom

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_SmartHome.PTZPosition):
                return NotImplemented
            else:
                if self.pan != other.pan:
                    return False
                if self.tilt != other.tilt:
                    return False
                if self.zoom != other.zoom:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_PTZPosition)

        __repr__ = __str__

    _M_SmartHome._t_PTZPosition = IcePy.defineStruct('::SmartHome::PTZPosition', PTZPosition, (), (
        ('pan', (), IcePy._t_float),
        ('tilt', (), IcePy._t_float),
        ('zoom', (), IcePy._t_int)
    ))

    _M_SmartHome.PTZPosition = PTZPosition
    del PTZPosition

if 'PTZPreset' not in _M_SmartHome.__dict__:
    _M_SmartHome.PTZPreset = Ice.createTempClass()
    class PTZPreset(object):
        def __init__(self, name='', position=Ice._struct_marker):
            self.name = name
            if position is Ice._struct_marker:
                self.position = _M_SmartHome.PTZPosition()
            else:
                self.position = position

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_SmartHome.PTZPreset):
                return NotImplemented
            else:
                if self.name != other.name:
                    return False
                if self.position != other.position:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_PTZPreset)

        __repr__ = __str__

    _M_SmartHome._t_PTZPreset = IcePy.defineStruct('::SmartHome::PTZPreset', PTZPreset, (), (
        ('name', (), IcePy._t_string),
        ('position', (), _M_SmartHome._t_PTZPosition)
    ))

    _M_SmartHome.PTZPreset = PTZPreset
    del PTZPreset

if '_t_PresetList' not in _M_SmartHome.__dict__:
    _M_SmartHome._t_PresetList = IcePy.defineSequence('::SmartHome::PresetList', (), _M_SmartHome._t_PTZPreset)

if 'UnknownPresetException' not in _M_SmartHome.__dict__:
    _M_SmartHome.UnknownPresetException = Ice.createTempClass()
    class UnknownPresetException(Ice.UserException):
        def __init__(self, presetName='', availablePresets=None):
            self.presetName = presetName
            self.availablePresets = availablePresets

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHome::UnknownPresetException'

    _M_SmartHome._t_UnknownPresetException = IcePy.defineException('::SmartHome::UnknownPresetException', UnknownPresetException, (), False, None, (
        ('presetName', (), IcePy._t_string, False, 0),
        ('availablePresets', (), _M_SmartHome._t_PresetList, False, 0)
    ))
    UnknownPresetException._ice_type = _M_SmartHome._t_UnknownPresetException

    _M_SmartHome.UnknownPresetException = UnknownPresetException
    del UnknownPresetException

_M_SmartHome._t_PTZCamera = IcePy.defineValue('::SmartHome::PTZCamera', Ice.Value, -1, (), False, True, None, ())

if 'PTZCameraPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.PTZCameraPrx = Ice.createTempClass()
    class PTZCameraPrx(_M_SmartHome.FixedCameraPrx):

        def getPosition(self, context=None):
            return _M_SmartHome.PTZCamera._op_getPosition.invoke(self, ((), context))

        def getPositionAsync(self, context=None):
            return _M_SmartHome.PTZCamera._op_getPosition.invokeAsync(self, ((), context))

        def begin_getPosition(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.PTZCamera._op_getPosition.begin(self, ((), _response, _ex, _sent, context))

        def end_getPosition(self, _r):
            return _M_SmartHome.PTZCamera._op_getPosition.end(self, _r)

        def moveTo(self, position, context=None):
            return _M_SmartHome.PTZCamera._op_moveTo.invoke(self, ((position, ), context))

        def moveToAsync(self, position, context=None):
            return _M_SmartHome.PTZCamera._op_moveTo.invokeAsync(self, ((position, ), context))

        def begin_moveTo(self, position, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.PTZCamera._op_moveTo.begin(self, ((position, ), _response, _ex, _sent, context))

        def end_moveTo(self, _r):
            return _M_SmartHome.PTZCamera._op_moveTo.end(self, _r)

        def savePreset(self, preset, context=None):
            return _M_SmartHome.PTZCamera._op_savePreset.invoke(self, ((preset, ), context))

        def savePresetAsync(self, preset, context=None):
            return _M_SmartHome.PTZCamera._op_savePreset.invokeAsync(self, ((preset, ), context))

        def begin_savePreset(self, preset, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.PTZCamera._op_savePreset.begin(self, ((preset, ), _response, _ex, _sent, context))

        def end_savePreset(self, _r):
            return _M_SmartHome.PTZCamera._op_savePreset.end(self, _r)

        def removePreset(self, preset, context=None):
            return _M_SmartHome.PTZCamera._op_removePreset.invoke(self, ((preset, ), context))

        def removePresetAsync(self, preset, context=None):
            return _M_SmartHome.PTZCamera._op_removePreset.invokeAsync(self, ((preset, ), context))

        def begin_removePreset(self, preset, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.PTZCamera._op_removePreset.begin(self, ((preset, ), _response, _ex, _sent, context))

        def end_removePreset(self, _r):
            return _M_SmartHome.PTZCamera._op_removePreset.end(self, _r)

        def goToPreset(self, name, context=None):
            return _M_SmartHome.PTZCamera._op_goToPreset.invoke(self, ((name, ), context))

        def goToPresetAsync(self, name, context=None):
            return _M_SmartHome.PTZCamera._op_goToPreset.invokeAsync(self, ((name, ), context))

        def begin_goToPreset(self, name, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.PTZCamera._op_goToPreset.begin(self, ((name, ), _response, _ex, _sent, context))

        def end_goToPreset(self, _r):
            return _M_SmartHome.PTZCamera._op_goToPreset.end(self, _r)

        def getPresets(self, context=None):
            return _M_SmartHome.PTZCamera._op_getPresets.invoke(self, ((), context))

        def getPresetsAsync(self, context=None):
            return _M_SmartHome.PTZCamera._op_getPresets.invokeAsync(self, ((), context))

        def begin_getPresets(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.PTZCamera._op_getPresets.begin(self, ((), _response, _ex, _sent, context))

        def end_getPresets(self, _r):
            return _M_SmartHome.PTZCamera._op_getPresets.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.PTZCameraPrx.ice_checkedCast(proxy, '::SmartHome::PTZCamera', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.PTZCameraPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::PTZCamera'
    _M_SmartHome._t_PTZCameraPrx = IcePy.defineProxy('::SmartHome::PTZCamera', PTZCameraPrx)

    _M_SmartHome.PTZCameraPrx = PTZCameraPrx
    del PTZCameraPrx

    _M_SmartHome.PTZCamera = Ice.createTempClass()
    class PTZCamera(_M_SmartHome.FixedCamera):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::FixedCamera', '::SmartHome::PTZCamera')

        def ice_id(self, current=None):
            return '::SmartHome::PTZCamera'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::PTZCamera'

        def getPosition(self, current=None):
            raise NotImplementedError("servant method 'getPosition' not implemented")

        def moveTo(self, position, current=None):
            raise NotImplementedError("servant method 'moveTo' not implemented")

        def savePreset(self, preset, current=None):
            raise NotImplementedError("servant method 'savePreset' not implemented")

        def removePreset(self, preset, current=None):
            raise NotImplementedError("servant method 'removePreset' not implemented")

        def goToPreset(self, name, current=None):
            raise NotImplementedError("servant method 'goToPreset' not implemented")

        def getPresets(self, current=None):
            raise NotImplementedError("servant method 'getPresets' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_PTZCameraDisp)

        __repr__ = __str__

    _M_SmartHome._t_PTZCameraDisp = IcePy.defineClass('::SmartHome::PTZCamera', PTZCamera, (), None, (_M_SmartHome._t_FixedCameraDisp,))
    PTZCamera._ice_type = _M_SmartHome._t_PTZCameraDisp

    PTZCamera._op_getPosition = IcePy.Operation('getPosition', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_PTZPosition, False, 0), ())
    PTZCamera._op_moveTo = IcePy.Operation('moveTo', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), _M_SmartHome._t_PTZPosition, False, 0),), (), None, (_M_SmartHome._t_InvalidValueException,))
    PTZCamera._op_savePreset = IcePy.Operation('savePreset', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_SmartHome._t_PTZPreset, False, 0),), (), None, ())
    PTZCamera._op_removePreset = IcePy.Operation('removePreset', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_SmartHome._t_PTZPreset, False, 0),), (), None, ())
    PTZCamera._op_goToPreset = IcePy.Operation('goToPreset', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), IcePy._t_string, False, 0),), (), None, (_M_SmartHome._t_UnknownPresetException,))
    PTZCamera._op_getPresets = IcePy.Operation('getPresets', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_PresetList, False, 0), ())

    _M_SmartHome.PTZCamera = PTZCamera
    del PTZCamera

if 'DeviceType' not in _M_SmartHome.__dict__:
    _M_SmartHome.DeviceType = Ice.createTempClass()
    class DeviceType(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    DeviceType.Thermostat = DeviceType("Thermostat", 0)
    DeviceType.DimmableLight = DeviceType("DimmableLight", 1)
    DeviceType.RGBLight = DeviceType("RGBLight", 2)
    DeviceType.FixedCamera = DeviceType("FixedCamera", 3)
    DeviceType.PTZCamera = DeviceType("PTZCamera", 4)
    DeviceType._enumerators = { 0:DeviceType.Thermostat, 1:DeviceType.DimmableLight, 2:DeviceType.RGBLight, 3:DeviceType.FixedCamera, 4:DeviceType.PTZCamera }

    _M_SmartHome._t_DeviceType = IcePy.defineEnum('::SmartHome::DeviceType', DeviceType, (), DeviceType._enumerators)

    _M_SmartHome.DeviceType = DeviceType
    del DeviceType

if 'DeviceEntry' not in _M_SmartHome.__dict__:
    _M_SmartHome.DeviceEntry = Ice.createTempClass()
    class DeviceEntry(object):
        def __init__(self, identity='', type=_M_SmartHome.DeviceType.Thermostat, location=''):
            self.identity = identity
            self.type = type
            self.location = location

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.identity)
            _h = 5 * _h + Ice.getHash(self.type)
            _h = 5 * _h + Ice.getHash(self.location)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHome.DeviceEntry):
                return NotImplemented
            else:
                if self.identity is None or other.identity is None:
                    if self.identity != other.identity:
                        return (-1 if self.identity is None else 1)
                else:
                    if self.identity < other.identity:
                        return -1
                    elif self.identity > other.identity:
                        return 1
                if self.type is None or other.type is None:
                    if self.type != other.type:
                        return (-1 if self.type is None else 1)
                else:
                    if self.type < other.type:
                        return -1
                    elif self.type > other.type:
                        return 1
                if self.location is None or other.location is None:
                    if self.location != other.location:
                        return (-1 if self.location is None else 1)
                else:
                    if self.location < other.location:
                        return -1
                    elif self.location > other.location:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_DeviceEntry)

        __repr__ = __str__

    _M_SmartHome._t_DeviceEntry = IcePy.defineStruct('::SmartHome::DeviceEntry', DeviceEntry, (), (
        ('identity', (), IcePy._t_string),
        ('type', (), _M_SmartHome._t_DeviceType),
        ('location', (), IcePy._t_string)
    ))

    _M_SmartHome.DeviceEntry = DeviceEntry
    del DeviceEntry

if '_t_DeviceList' not in _M_SmartHome.__dict__:
    _M_SmartHome._t_DeviceList = IcePy.defineSequence('::SmartHome::DeviceList', (), _M_SmartHome._t_DeviceEntry)

_M_SmartHome._t_DeviceRegistry = IcePy.defineValue('::SmartHome::DeviceRegistry', Ice.Value, -1, (), False, True, None, ())

if 'DeviceRegistryPrx' not in _M_SmartHome.__dict__:
    _M_SmartHome.DeviceRegistryPrx = Ice.createTempClass()
    class DeviceRegistryPrx(Ice.ObjectPrx):

        def listDevices(self, context=None):
            return _M_SmartHome.DeviceRegistry._op_listDevices.invoke(self, ((), context))

        def listDevicesAsync(self, context=None):
            return _M_SmartHome.DeviceRegistry._op_listDevices.invokeAsync(self, ((), context))

        def begin_listDevices(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DeviceRegistry._op_listDevices.begin(self, ((), _response, _ex, _sent, context))

        def end_listDevices(self, _r):
            return _M_SmartHome.DeviceRegistry._op_listDevices.end(self, _r)

        def listDevicesByType(self, type, context=None):
            return _M_SmartHome.DeviceRegistry._op_listDevicesByType.invoke(self, ((type, ), context))

        def listDevicesByTypeAsync(self, type, context=None):
            return _M_SmartHome.DeviceRegistry._op_listDevicesByType.invokeAsync(self, ((type, ), context))

        def begin_listDevicesByType(self, type, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHome.DeviceRegistry._op_listDevicesByType.begin(self, ((type, ), _response, _ex, _sent, context))

        def end_listDevicesByType(self, _r):
            return _M_SmartHome.DeviceRegistry._op_listDevicesByType.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHome.DeviceRegistryPrx.ice_checkedCast(proxy, '::SmartHome::DeviceRegistry', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHome.DeviceRegistryPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHome::DeviceRegistry'
    _M_SmartHome._t_DeviceRegistryPrx = IcePy.defineProxy('::SmartHome::DeviceRegistry', DeviceRegistryPrx)

    _M_SmartHome.DeviceRegistryPrx = DeviceRegistryPrx
    del DeviceRegistryPrx

    _M_SmartHome.DeviceRegistry = Ice.createTempClass()
    class DeviceRegistry(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHome::DeviceRegistry')

        def ice_id(self, current=None):
            return '::SmartHome::DeviceRegistry'

        @staticmethod
        def ice_staticId():
            return '::SmartHome::DeviceRegistry'

        def listDevices(self, current=None):
            raise NotImplementedError("servant method 'listDevices' not implemented")

        def listDevicesByType(self, type, current=None):
            raise NotImplementedError("servant method 'listDevicesByType' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHome._t_DeviceRegistryDisp)

        __repr__ = __str__

    _M_SmartHome._t_DeviceRegistryDisp = IcePy.defineClass('::SmartHome::DeviceRegistry', DeviceRegistry, (), None, ())
    DeviceRegistry._ice_type = _M_SmartHome._t_DeviceRegistryDisp

    DeviceRegistry._op_listDevices = IcePy.Operation('listDevices', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_SmartHome._t_DeviceList, False, 0), ())
    DeviceRegistry._op_listDevicesByType = IcePy.Operation('listDevicesByType', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), _M_SmartHome._t_DeviceType, False, 0),), (), ((), _M_SmartHome._t_DeviceList, False, 0), ())

    _M_SmartHome.DeviceRegistry = DeviceRegistry
    del DeviceRegistry

# End of module SmartHome
